# Stop hook: append rtk session stats to ~/.claude/reports/token-usage.md.
# Idempotent per-day heading. One row per session.

$ErrorActionPreference = 'SilentlyContinue'

$ClaudeRoot = if ($env:CLAUDE_CONFIG_DIR) { $env:CLAUDE_CONFIG_DIR } else { Join-Path $env:USERPROFILE '.claude' }
$reportsDir = Join-Path $ClaudeRoot 'reports'
$file       = Join-Path $reportsDir 'token-usage.md'
if (-not (Test-Path $reportsDir)) { New-Item -ItemType Directory -Force -Path $reportsDir | Out-Null }

# Pull rtk gain session JSON (best-effort; rtk may be missing or schema may differ)
$json = $null
try {
    $raw = & rtk gain --session --json 2>$null
    if ($raw) { $json = ($raw -join "`n") | ConvertFrom-Json }
} catch {}

$today     = Get-Date -Format 'yyyy-MM-dd'
$timestamp = Get-Date -Format 'HH:mm'

$saved = 'n/a'
$ratio = 'n/a'
$count = 'n/a'
if ($json) {
    $sess = $null
    if     ($json.session)  { $sess = $json.session }
    elseif ($json.PSObject.Properties['session_total']) { $sess = $json.session_total }
    else { $sess = $json }
    if ($sess.total_saved)  { $saved = $sess.total_saved }
    if ($sess.savings_ratio) { $ratio = "{0:N1}%" -f ([double]$sess.savings_ratio * 100) }
    if ($sess.commands)     { $count = $sess.commands }
}

$row = "| $timestamp | $count | $saved | $ratio |"

if (-not (Test-Path $file)) {
    $header = @(
        '# Token Usage Report',
        '',
        '_Auto-generated by Stop hook (`token-report.ps1`). Append-only. One row per session._',
        ''
    ) -join "`n"
    Set-Content -Path $file -Value $header -Encoding UTF8
}

$content = Get-Content $file -Raw -Encoding UTF8
$dayHeader = "## $today"
if (-not $content -or ($content -notmatch [regex]::Escape($dayHeader))) {
    $tableHeader = "`n$dayHeader`n`n| Time | Commands | Tokens saved (rtk) | Saved ratio |`n|---|---|---|---|"
    Add-Content -Path $file -Value $tableHeader -Encoding UTF8
}
Add-Content -Path $file -Value $row -Encoding UTF8

# Audit Domain: missed savings projection — hook compliance audit.
# After Token Domain hook is active, this output should approach zero.
try {
    $disc = & rtk discover --all 2>$null
    if ($disc) {
        Add-Content -Path $file -Value (
            "`n### rtk discover (missed savings)`n``````n" +
            ($disc -join "`n") + "`n``````n"
        ) -Encoding UTF8
    }
} catch {}

exit 0
