# Claude Code Session Automation

_Architecture document. Static sections: architect-maintained. Marked sections between `<!-- AUTO:* -->` tags are regenerated by `hooks/update-docs.ps1` on every SessionStart — do not edit those sections by hand._

**Last verified**: 2026-04-28T18:05:23+09:00 <!-- AUTO:TIMESTAMP -->

---

## Why this exists

Claude Code loads `%USERPROFILE%\.claude\CLAUDE.md`, rule files, and related configs at every session start. If Anthropic updates official guidance (CLAUDE.md size limits, hook API shape, settings schema, best practices), those local rules silently become stale. Manual checking is unreliable at scale.

This automation closes that gap with three responsibilities:

1. **Upstream detection** — SHA256-based diff of 5 key official docs + GitHub Releases API for the CLI itself. No user action required.
2. **Non-intrusive notification** — changes accumulate in `docs-updates.md`. No popups, no blocking, no auto-edits.
3. **Plan hygiene** — plan files older than 60 days are archived so `%USERPROFILE%\.claude\plans\` stays navigable.

---

## Data flow

```
Claude Code SessionStart
         |
         v
 session-start.ps1  ──── calls (sequentially) ────────────────────────────────┐
         |                                                                      |
         |──► update-docs.ps1         regenerate AUTOMATION.md marked sections |
         |──► archive-plans.ps1       move 60d+ plan files to plans/archive/   |
         v──► check-updates.ps1       24h gate check                           |
                   |                                                            |
              passed 24h?                                                       |
              no ──► exit (noop)                                               |
              yes                                                               |
                   |                                                            |
                   v                                                            |
         Start-Process detached ──► check-updates-worker.ps1                  |
                                              |                                |
                              ┌───────────────┴──────────────────┐            |
                              v                                   v            |
                    GitHub Releases API             5x docs SHA256 diff        |
                    /anthropics/claude-code         memory / hooks /           |
                    /releases/latest                best-practices /           |
                              |                     settings /                 |
                              └───────────────┬─────context-window             |
                                              v                                |
                                      any change?                              |
                                      no ──► exit silently                    |
                                      yes                                      |
                                              v                                |
                                 %USERPROFILE%\.claude\docs-updates.md                   |
                                 (append entry, user reads at leisure)         |
                                                                               |
session starts normally — zero blocking latency ◄──────────────────────────────┘
```

---

## Design decisions

| Decision | Choice | Rationale |
|---|---|---|
| Trigger mechanism | `SessionStart` hook in `settings.json` | Anthropic's documented API — survives Claude Code upgrades without custom tooling |
| Session start latency | `async: true` + detached worker | `session-start.ps1` completes in <100ms; network work happens detached after session opens |
| Worker isolation | `Start-Process -WindowStyle Hidden` | Detached process survives when PowerShell parent exits; jobs do not |
| Network failures | `try/catch` + `SilentlyContinue` | Network errors must never block a dev session |
| Auto-apply | Never | Docs are prose; translating to rule changes requires human judgment. Silent drift is worse than no automation |
| Hash algorithm | SHA256 | Detects any content change; immune to CDN `Last-Modified` header inconsistencies |
| ETag vs hash | Hash | `Invoke-WebRequest` in PowerShell 5.1 does not expose ETag cleanly; SHA256 is explicit and portable |
| First-run behavior | Silent baseline | Establishes cache without generating noise; notification only fires on next change |
| Rate limit guard | 24h timestamp file | GitHub API: 60 req/h unauthenticated; `last-check.txt` prevents hammering across rapid restarts |
| Archive threshold | 60 days | Long enough that active WIP plans survive; short enough to prevent indefinite accumulation |
| Doc update strategy | Marker-based in-place replacement | Preserves static architect commentary while keeping generated data current |
| PowerShell encoding | ASCII-safe separators (`->`) | PowerShell 5.1 defaults to ANSI codepage; em-dash (U+2014) gets corrupted — explicit ASCII prevents this |

---

## Compaction Policy (REWIND CONTEXT)

When Claude Code reaches its context budget and triggers compaction, the goal is to **preserve the smallest set of artifacts that lets the next turn continue coherently**. The PreCompact and PostCompact hooks enforce this.

### MUST preserve (load-bearing)

- Active plan file under `plans/` (most recent mtime)
- All rule + architecture files: `CLAUDE.md`, `RTK.md`, `ARCHITECTURE.md`, `AUTOMATION.md`, `HARNESS_ARCHITECTURE.md`, project `.claude/rules/`
- `settings.json`
- Per-project `MEMORY.md` index for active project (resolved via `active-projects.json`)
- Memory topic files (`projects/<name>/memory/*.md`) modified in last 30 days

### MAY drop (regenerable or stale)

- Plans older than 60 days (already archived by `archive-plans.ps1`)
- `.docs-cache/*` — regenerable from upstream on next 24h gate
- `cleanup.log` — append-only audit, not load-bearing
- Completed todo lists from prior turns
- Intermediate exploration output (file reads, grep results) — re-fetchable

### Hook responsibilities

- `precompact-snapshot.ps1`: hard-link the MUST-preserve set into `backups/precompact-<ts>-<sid>/` so a postmortem can recover anything dropped accidentally.
- `postcompact-verify.ps1`: confirm `@import` chains in `CLAUDE.md`/`RTK.md` still resolve and the active plan file is still readable. Surface broken refs via stderr — Claude reacts in the next turn.
- `statusline.ps1`: shows `compact:warn` if the most recent post-compact verification flagged a loss.

### Anti-pattern

Manually editing `precompact-snapshot.ps1` to also snapshot `projects/<name>/sessions/` or `file-history/` is a **FOMO trap** — the snapshot grows unboundedly with no recovery use case. Stay with the MUST-preserve set above unless an incident proves otherwise.

---

## Files

<!-- AUTO:SCRIPTS-START -->
| Script | Description | Modified |
|---|---|---|
| `archive-plans.ps1` | Archive plan files older than 60 days into ~/.claude/plans/archive/. | 2026-04-28 |
| `auto-pin.ps1` | Auto-register current project into active-projects.json pinned list on SessionStart. | 2026-04-28 |
| `check-updates.ps1` | SessionStart trigger: 24h gate, then spawn worker detached. | 2026-04-28 |
| `check-updates-worker.ps1` | Detached worker: SHA-diff Claude Code release + key official docs; append findings to docs-updates.md and queue impact sections to review-needed.md. | 2026-04-28 |
| `drift-detect-worker.ps1` | Drift detector worker: drain .drift-queue, append findings to ~/.claude/review-needed.md. | 2026-04-28 |
| `drift-enqueue.ps1` | PostToolUse hook: enqueue edited file paths and dep-install commands. | 2026-04-28 |
| `inject-runtime-ctx.ps1` | UserPromptSubmit hook: inject git runtime context only when the repo is dirty. | 2026-04-28 |
| `memory-backup.ps1` | Weekly snapshot of every project memory dir into ~/.claude/backups/memory-YYYYWW.zip. | 2026-04-28 |
| `memory-lint.ps1` | Lightweight memory integrity check on SessionStart. | 2026-04-28 |
| `oneshot-consolidate.ps1` | One-shot D-drive consolidation worker. | 2026-04-28 |
| `postcompact-verify.ps1` | PostCompact hook: verify @import chain integrity in core AI-consumed files | 2026-04-28 |
| `precompact-snapshot.ps1` | PreCompact hook: snapshot project memory + active plans via hard-links. | 2026-04-28 |
| `session-start.ps1` | SessionStart entry point. Calls all session-start tasks in order. | 2026-04-28 |
| `token-report.ps1` | Stop hook: append rtk session stats to ~/.claude/reports/token-usage.md. | 2026-04-28 |
| `update-docs.ps1` | Regenerate AUTO-marked sections in ~/.claude/AUTOMATION.md on every session start. | 2026-04-28 |
<!-- AUTO:SCRIPTS-END -->

---

## Hook events

_Sourced from `%USERPROFILE%\.claude\settings.json`. Auto-regenerated on SessionStart by `update-docs.ps1`._

<!-- AUTO:HOOK-EVENTS-START -->
| Event | Matcher | Async | Command (truncated) |
|---|---|---|---|
| PostCompact | * | yes | `powershell.exe -NonInteractive -File "%USERPROFILE%/.claude/hooks/postcompact...` |
| PostToolUse | Edit|Write|Bash | yes | `powershell.exe -NonInteractive -File "%USERPROFILE%/.claude/hooks/drift-enque...` |
| PreCompact | * | no | `powershell.exe -NonInteractive -File "%USERPROFILE%/.claude/hooks/precompact-...` |
| PreToolUse | Bash | no | `node "%USERPROFILE%/.claude/hooks/rtk-prerewrite.js"` |
| SessionEnd | * | yes | `powershell.exe -NonInteractive -File "%USERPROFILE%/.claude/cleanup.ps1"` |
| SessionEnd | * | yes | `powershell.exe -NonInteractive -File "%USERPROFILE%/.claude/hooks/drift-detec...` |
| SessionStart | * | no | `powershell.exe -NonInteractive -File "%USERPROFILE%/.claude/hooks/session-sta...` |
| Stop | * | yes | `powershell.exe -NonInteractive -File "%USERPROFILE%/.claude/hooks/token-repor...` |
| UserPromptSubmit | * | no | `powershell.exe -NonInteractive -File "%USERPROFILE%/.claude/hooks/inject-runt...` |
<!-- AUTO:HOOK-EVENTS-END -->

---

## Skills

_Sourced from `%USERPROFILE%\.claude\skills\<name>\SKILL.md` frontmatter (`name` + `description`)._

<!-- AUTO:SKILLS-START -->
| Skill | Description |
|---|---|
| _(none registered)_ |  |
<!-- AUTO:SKILLS-END -->

---

## Monitored sources

| Source | Cache key | What it detects |
|---|---|---|
| Claude Code release | `release-tag.txt` | New CLI versions (bug fixes, new hook events, settings changes) |
| `memory.md` | `memory.sha256` | CLAUDE.md best practices, size limits (currently 200 lines) |
| `hooks.md` | `hooks.sha256` | Hook event types, payload schema, timeout behavior |
| `best-practices.md` | `best-practices.sha256` | General guidance, anti-patterns |
| `settings.md` | `settings.sha256` | `settings.json` supported keys and defaults |
| `context-window.md` | `context-window.sha256` | Startup context budget breakdown (affects rule file sizing) |

---

## Cache layout

```
%USERPROFILE%\.claude\.docs-cache\
├── last-check.txt          # ISO8601 timestamp of last trigger run (24h gate)
├── release-tag.txt         # Last seen Claude Code release tag (e.g. v2.1.119)
├── memory.sha256           # SHA256 of last fetched memory.md
├── hooks.sha256
├── best-practices.sha256
├── settings.sha256
└── context-window.sha256
```

---

## Output format

`%USERPROFILE%\.claude\docs-updates.md` is append-only. Each session that detects changes appends a dated block:

```markdown
## 2026-04-27
- **Claude Code release**: v2.1.120 (was: v2.1.119) -> https://github.com/...
- **Doc updated**: memory -> https://code.claude.com/docs/en/memory.md
```

The user reviews this file and decides whether to update `AGENTS.md`, `CLAUDE.md`, or global rules. Nothing is auto-applied.

---

## Extending

### Add a new monitored doc page

1. Open `%USERPROFILE%\.claude\hooks\check-updates-worker.ps1`
2. Add an entry to the `$docs` array:
   ```powershell
   @{ name = 'your-page'; url = 'https://code.claude.com/docs/en/your-page.md' }
   ```
3. Done — next session start populates the baseline hash silently; subsequent changes trigger notification.

### Add a new session-start task

1. Create `%USERPROFILE%\.claude\hooks\your-task.ps1`. First line **must** be a `# Short description` comment — this feeds `update-docs.ps1`.
2. Add `& "$PSScriptRoot\your-task.ps1"` to `session-start.ps1`.
3. `update-docs.ps1` auto-discovers all `*.ps1` in `hooks/` on next session and updates this document.

### Force a refresh (bypass 24h gate)

```powershell
Remove-Item %USERPROFILE%\.claude\.docs-cache\last-check.txt
# Then restart Claude Code or run session-start.ps1 manually
```

---

## Troubleshooting

| Symptom | Likely cause | Fix |
|---|---|---|
| `docs-updates.md` never created | Worker failing silently | Run `check-updates-worker.ps1` in an interactive PowerShell to see errors |
| Only `release-tag.txt` in cache, no `.sha256` files | Stale worker before the `byte[]` fix | Delete cache dir and run worker again |
| Release tag not updating | GitHub API rate limit (60/h) | Check `last-check.txt` timestamp — if <24h ago, wait |
| `AUTOMATION.md` markers not updating | `update-docs.ps1` not called | Verify `session-start.ps1` includes the call |
| Plan files not archived | All files < 60 days old | Expected — archive only triggers after 60 days of inactivity |
| Korean text garbled in docs | PowerShell ANSI codepage | All scripts use `-Encoding UTF8`; ensure editor reads as UTF-8 |

---

## Related files

| File | Role |
|---|---|
| `%USERPROFILE%\.claude\settings.json` | Registers `SessionStart` hook pointing to `session-start.ps1` |
| `%USERPROFILE%\.claude\docs-updates.md` | Auto-created on first detected change; append-only notification log |
| `%USERPROFILE%\.claude\.docs-cache\` | Hash/tag/timestamp cache; safe to delete for forced refresh |
| `%USERPROFILE%\.claude\plans\archive\` | Destination for 60d+ archived plan files |
